CREATE TABLE IF NOT EXISTS `bikefits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `klant_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `datum` date NOT NULL,
  `testtype` varchar(255) DEFAULT NULL,
  `type_fitting` varchar(255) DEFAULT NULL,
  `lengte_cm` decimal(5,2) DEFAULT NULL,
  `binnenbeenlengte_cm` decimal(5,2) DEFAULT NULL,
  `armlengte_cm` decimal(5,2) DEFAULT NULL,
  `romplengte_cm` decimal(5,2) DEFAULT NULL,
  `schouderbreedte_cm` decimal(5,2) DEFAULT NULL,
  `zadel_trapas_hoek` decimal(5,2) DEFAULT NULL,
  `zadel_trapas_afstand` decimal(5,2) DEFAULT NULL,
  `stuur_trapas_hoek` decimal(5,2) DEFAULT NULL,
  `stuur_trapas_afstand` decimal(5,2) DEFAULT NULL,
  `aanpassingen_zadel` decimal(5,2) DEFAULT NULL,
  `aanpassingen_setback` decimal(5,2) DEFAULT NULL,
  `aanpassingen_reach` decimal(5,2) DEFAULT NULL,
  `aanpassingen_drop` decimal(5,2) DEFAULT NULL,
  `aanpassingen_stuurpen_aan` tinyint(1) DEFAULT NULL,
  `aanpassingen_stuurpen_pre` text,
  `aanpassingen_stuurpen_post` text,
  `type_zadel` varchar(255) DEFAULT NULL,
  `zadeltil` decimal(5,2) DEFAULT NULL,
  `zadelbreedte` decimal(5,2) DEFAULT NULL,
  `zadel_lengte_center_top` decimal(5,2) DEFAULT NULL,
  `rotatie_aanpassingen` text,
  `inclinatie_aanpassingen` text,
  `ophoging_li` decimal(5,2) DEFAULT NULL,
  `ophoging_re` decimal(5,2) DEFAULT NULL,
  `fietsmerk` varchar(255) DEFAULT NULL,
  `kadermaat` varchar(255) DEFAULT NULL,
  `frametype` varchar(255) DEFAULT NULL,
  `algemene_klachten` text,
  `beenlengteverschil` tinyint(1) DEFAULT NULL,
  `beenlengteverschil_cm` varchar(255) DEFAULT NULL,
  `lenigheid_hamstrings` varchar(255) DEFAULT NULL,
  `steunzolen` tinyint(1) DEFAULT NULL,
  `steunzolen_reden` text,
  `schoenmaat` varchar(255) DEFAULT NULL,
  `voetbreedte` varchar(255) DEFAULT NULL,
  `straight_leg_raise_links` varchar(255) DEFAULT NULL,
  `straight_leg_raise_rechts` varchar(255) DEFAULT NULL,
  `knieflexie_links` varchar(255) DEFAULT NULL,
  `knieflexie_rechts` varchar(255) DEFAULT NULL,
  `heup_endorotatie_links` varchar(255) DEFAULT NULL,
  `heup_endorotatie_rechts` varchar(255) DEFAULT NULL,
  `heup_exorotatie_links` varchar(255) DEFAULT NULL,
  `heup_exorotatie_rechts` varchar(255) DEFAULT NULL,
  `enkeldorsiflexie_links` varchar(255) DEFAULT NULL,
  `enkeldorsiflexie_rechts` varchar(255) DEFAULT NULL,
  `one_leg_squat_links` varchar(255) DEFAULT NULL,
  `one_leg_squat_rechts` varchar(255) DEFAULT NULL,
  `nieuw_testzadel` tinyint(1) DEFAULT NULL,
  `opmerkingen` text,
  `interne_opmerkingen` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `bikefits_klant_id_foreign` (`klant_id`),
  KEY `bikefits_user_id_foreign` (`user_id`),
  CONSTRAINT `bikefits_klant_id_foreign` FOREIGN KEY (`klant_id`) REFERENCES `klanten` (`id`) ON DELETE CASCADE,
  CONSTRAINT `bikefits_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;