    protected $fillable = [
        'user_id',
        'voornaam',
        'achternaam',
        'email',
        'telefoon',
        'adres',
        'stad', 
        'postcode',
        'land',
        'geboortedatum',
        'gewicht',
        'lengte',
        'medische_info',
        'doelstellingen',
        'sport_ervaring',
        'opmerkingen',
    ];